name: Send APK via Email

on:
  push:
    branches:
      - main

jobs:
  send_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Nodemailer
        run: npm install nodemailer

      - name: Send APK via Email
        run: |
          const nodemailer = require('nodemailer');

          const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
              user: process.env.EMAIL_ADDRESS,
              pass: process.env.EMAIL_PASSWORD,
            },
          });

          const mailOptions = {
            from: process.env.EMAIL_ADDRESS,
            to: 'ragenmah99@example.com', // Enter the recipient's email address
            subject: 'APK File',
            text: 'Here is the APK file you requested.',
            attachments: [
              {
                path: 'build/app/outputs/apk/release/app-release.apk', // Update with the path to your APK file
              },
            ],
          };

          transporter.sendMail(mailOptions, function (error, info) {
            if (error) {
              console.error('Error sending email:', error);
            } else {
              console.log('Email sent:', info.response);
            }
          });
